name: Run Main Script

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # 启用 pip 缓存
          cache-dependency-path: requirements.txt # 指定依赖文件路径

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: python -m src.main
        env:
          R2_ENDPOINT_URL: https://379d24c1353d186a0d34cc685f105946.r2.cloudflarestorage.com
          R2_ACCESS_KEY_ID: 5f6f00b50f105fe1be133aae0df84a52
          R2_SECRET_ACCESS_KEY: 882f2fa8a6e61dd3485df0a29f45b171eb3750c7b5c811fc2f646216ddeb111d
          R2_BUCKET_NAME: pub
          CLOUDFLARE_API_TOKEN: BN_Id1JTtOcR-eRe_nUrA_AQ2QM3n7dhw0WFGOsA
          CLOUDFLARE_ZONE_ID: 601c52991b57fd97b2f001888c48ed27
